name: test_emc2dev
channels:
  - defaults
  - conda-forge
  - pypi
dependencies:
  # - sphinx=8.2.3
  # - myst-parser=4.0.1
  # - sphinx-material=0.0.36
  - numpy
  # - matplotlib
  # - jupyter-sphinx
  # - sphinx-thebe
